language: cpp
sudo: required
os:
  - linux
  - osx
dist: trusty
notifications:
  email:
  - jmirabel@laas.fr
addons:
  apt:
    packages:
      - libboost-filesystem-dev
      - libboost-system-dev
      - libtinyxml-dev
branches:
  only:
  - master
  - devel
compiler:
  - gcc
before_install:
  - export ROOT_DIR=`pwd`
  - export DEVEL_DIR="$ROOT_DIR/_travis"
  - export TRAVIS_SUBMODULE="$ROOT_DIR/.travis-submodule"
install:
  - git submodule --quiet update --init
  - ${TRAVIS_SUBMODULE}/install
script: ${TRAVIS_SUBMODULE}/script
